version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "db:/var/lib/postgresql"
    ports:
      - "5432:5432"

volumes:
  db:
